.TH tempread 8
.SH NAME
tempread \- read tempareture of device read
.SH SYNOPSIS
.B tempread
[\fB\-v\fR]
[\fB\-d\fR \fIDECIVEID\fR]
.IR string ...
.SH DESCRIPTION
.B tempread
whow the tempread device read
.SH OPTIONS
.TP
.BR \-d ", " deviceid =\fISTRING\fR
show the tempareture read of device with deviceid
.TP
.BR \-v "
show the whole file to debug